import { test, expect, snapshot, deviceApplication } from './fixtures'
import type { TerminalRequest } from '../../src/shared/terminal'

// 使用真实 xterm；通过复制全部输出检查已经渲染进入终端缓冲区的内容。
async function request(app: { calls: (method: 'startTerminal') => Promise<unknown[][]> }): Promise<TerminalRequest> {
  await expect.poll(async () => (await app.calls('startTerminal')).length).toBe(1)
  return (await app.calls('startTerminal'))[0]![0] as TerminalRequest
}

test('快捷命令搜索、包名预填、参数校验、撤销和键盘关闭', async ({ app, page }) => {
  await app.open(snapshot({ selectedDeviceApplication: deviceApplication }))
  await page.getByRole('button', { name: 'ADB 终端', exact: true }).click()
  const panel = page.getByRole('region', { name: 'ADB 终端', exact: true })
  const input = panel.getByRole('textbox', { name: 'ADB 命令' })
  await expect(panel).toContainText('Server：127.0.0.1:5042')
  await input.fill('adb shell echo draft')
  await panel.getByRole('button', { name: '全部系统属性' }).click()
  await expect(input).toHaveValue('adb shell getprop')
  await panel.getByRole('button', { name: '撤销填入' }).click()
  await expect(input).toHaveValue('adb shell echo draft')
  await input.press('Control+k')
  const dialog = page.getByRole('dialog', { name: '快捷命令库' })
  const search = dialog.getByRole('textbox', { name: '搜索快捷命令' })
  await search.fill('应用详情')
  await expect(dialog.getByRole('textbox', { name: '应用包名' })).toHaveValue(deviceApplication.packageName)
  await dialog.getByRole('textbox', { name: '应用包名' }).fill('')
  await expect(dialog.getByRole('button', { name: '填入命令' })).toBeDisabled()
  await dialog.getByRole('textbox', { name: '应用包名' }).fill('com.example.other')
  await expect(dialog.getByText('adb shell dumpsys package com.example.other', { exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: '填入命令' }).click()
  await expect(dialog).toBeHidden()
  await expect(input).toHaveValue('adb shell dumpsys package com.example.other')
  await app.expectCalls('startTerminal', [])
  await input.press('Control+k')
  await search.fill('no-such-command-xyz')
  await expect(dialog.getByText('没有匹配命令，试试其他关键词或分类。')).toBeVisible()
  await search.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(input).toBeFocused()
})

test('执行绑定设备、真实输出与回压确认、复制、历史、粘贴和清屏', async ({ app, page }) => {
  await app.open()
  await page.getByRole('button', { name: 'ADB 终端', exact: true }).click()
  const panel = page.getByRole('region', { name: 'ADB 终端', exact: true })
  const input = panel.getByRole('textbox', { name: 'ADB 命令' })
  await input.fill(' adb devices -l ')
  await input.press('Enter')
  const started = await request(app)
  expect(started).toMatchObject({ command: 'adb devices -l', serial: 'E2E-USB-001' })
  expect(started.cols).toBeGreaterThanOrEqual(20)
  expect(started.rows).toBeGreaterThanOrEqual(5)
  await app.emit({ id: started.id, type: 'started', mode: 'command', serial: started.serial })
  const output = 'E2E-USB-001\tdevice\n'
  await app.emit({ id: started.id, type: 'output', data: output })
  await app.expectCalls('acknowledgeTerminal', [[started.id, output.length]])
  await app.emit({ id: 'stale-session', type: 'output', data: 'STALE_DEVICE_OUTPUT' })
  await panel.getByRole('button', { name: '复制', exact: true }).click()
  const copied = (await app.calls('copyTerminalText'))[0]![0] as string
  expect(copied).toContain('E2E-USB-001')
  expect(copied).toContain('device')
  expect(copied).not.toContain('STALE_DEVICE_OUTPUT')
  await app.emit({ id: started.id, type: 'exit', code: 0, stopped: false, message: '命令已结束' })
  await expect(input).toBeVisible()
  await input.fill('draft')
  await input.press('ArrowUp')
  await expect(input).toHaveValue('adb devices -l')
  await input.press('ArrowDown')
  await expect(input).toHaveValue('draft')
  await input.fill('')
  await app.reply('readTerminalClipboard', 'adb shell\ngetprop')
  await panel.getByRole('button', { name: '粘贴', exact: true }).click()
  await expect(input).toHaveValue('adb shell getprop')
  expect(await app.calls('startTerminal')).toHaveLength(1)
  await panel.getByRole('button', { name: '清屏', exact: true }).click()
  await panel.getByRole('button', { name: '复制', exact: true }).click()
  expect((await app.calls('copyTerminalText'))[1]![0]).not.toContain('E2E-USB-001')
})

test('持续 Shell 可收起再打开，快捷输入不带回车，结束后解除忙碌', async ({ app, page }) => {
  const initial = snapshot()
  await app.open(initial)
  await page.getByRole('button', { name: 'ADB 终端', exact: true }).click()
  const panel = page.getByRole('region', { name: 'ADB 终端', exact: true })
  await panel.getByRole('textbox', { name: 'ADB 命令' }).fill('adb shell')
  await panel.getByRole('button', { name: '执行', exact: true }).click()
  const started = await request(app)
  await app.emit({ id: started.id, type: 'started', mode: 'shell', serial: started.serial })
  await app.publish({ ...initial, busy: true })
  await expect(panel.getByText('设备 Shell', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Home', exact: true })).toBeDisabled()
  await panel.getByRole('button', { name: '全部系统属性' }).click()
  await app.expectCalls('writeTerminal', [[started.id, 'getprop']])
  await expect(panel.getByRole('button', { name: '进入设备 Shell' })).toBeDisabled()
  await panel.locator('.xterm-helper-textarea').press('Control+c')
  await app.expectCalls('writeTerminal', [[started.id, 'getprop'], [started.id, '\u0003']])
  await app.expectCalls('stopTerminal', [])
  await panel.getByRole('button', { name: '收起终端' }).click()
  await expect(panel).toBeHidden()
  await app.expectCalls('stopTerminal', [])
  await page.getByRole('button', { name: 'ADB 终端', exact: true }).click()
  await expect(panel.getByText('设备 Shell', { exact: true })).toBeVisible()
  expect(await app.calls('startTerminal')).toHaveLength(1)
  await panel.getByRole('button', { name: '结束会话' }).click()
  await app.expectCalls('stopTerminal', [[started.id]])
  await app.emit({ id: started.id, type: 'exit', code: null, stopped: true, message: '会话已结束' })
  await app.publish(initial)
  await expect(panel.getByRole('textbox', { name: 'ADB 命令' })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Home', exact: true })).toBeEnabled()
})

test('普通命令 Ctrl+C 停止客户端，工作流忙碌禁止新命令', async ({ app, page }) => {
  await app.open()
  await page.getByRole('button', { name: 'ADB 终端', exact: true }).click()
  const panel = page.getByRole('region', { name: 'ADB 终端', exact: true })
  await panel.getByRole('textbox', { name: 'ADB 命令' }).fill('adb logcat')
  await panel.getByRole('button', { name: '执行', exact: true }).click()
  const started = await request(app)
  await app.emit({ id: started.id, type: 'started', mode: 'command', serial: started.serial })
  await panel.locator('.xterm-helper-textarea').press('Control+c')
  await app.expectCalls('stopTerminal', [[started.id]])
  await app.expectCalls('writeTerminal', [])
  await app.emit({ id: started.id, type: 'exit', code: null, stopped: true, message: '已停止' })
  await app.publish(snapshot({ busy: true }))
  await expect(panel.getByRole('textbox', { name: 'ADB 命令' })).toBeDisabled()
  await expect(panel.getByRole('button', { name: '执行', exact: true })).toBeDisabled()
})

test('终端启动失败呈现错误并允许修正后重试', async ({ app, page }) => {
  await app.open()
  await page.getByRole('button', { name: 'ADB 终端', exact: true }).click()
  const panel = page.getByRole('region', { name: 'ADB 终端', exact: true })
  await app.reject('startTerminal', '当前命令不受支持。')
  await panel.getByRole('textbox', { name: 'ADB 命令' }).fill('unsupported')
  await panel.getByRole('button', { name: '执行', exact: true }).click()
  await expect(panel.getByRole('alert')).toHaveText('当前命令不受支持。')
  await expect(panel.getByRole('textbox', { name: 'ADB 命令' })).toBeEnabled()
  await panel.getByRole('textbox', { name: 'ADB 命令' }).fill('adb devices')
  await panel.getByRole('button', { name: '执行', exact: true }).click()
  await expect.poll(async () => (await app.calls('startTerminal')).length).toBe(2)
  await expect(panel.getByRole('alert')).toHaveCount(0)
  expect((await app.calls('startTerminal'))[1]![0]).toMatchObject({ command: 'adb devices', serial: 'E2E-USB-001' })
})

test('ADB 未就绪时禁止终端提交，恢复后可输入', async ({ app, page }) => {
  const initial = snapshot()
  await app.open({ ...initial, adb: { ...initial.adb, state: 'error', message: 'ADB 启动失败' } })
  await expect(page.locator('.device-status')).toHaveText('ADB 启动失败')
  await page.getByRole('button', { name: 'ADB 终端', exact: true }).click()
  const panel = page.getByRole('region', { name: 'ADB 终端', exact: true })
  await expect(panel.getByRole('textbox', { name: 'ADB 命令' })).toBeDisabled()
  await expect(panel.getByRole('button', { name: '执行', exact: true })).toBeDisabled()
  await app.expectCalls('startTerminal', [])
  await app.publish(initial)
  await expect(panel.getByRole('textbox', { name: 'ADB 命令' })).toBeEnabled()
})
