export const IPC_CHANNELS = {
  terminalStart: 'terminal:start',
  terminalWrite: 'terminal:write',
  terminalStop: 'terminal:stop',
  terminalAcknowledge: 'terminal:acknowledge',
  terminalEvent: 'terminal:event',
  terminalCopy: 'terminal:copy',
  terminalPaste: 'terminal:paste',
  getSnapshot: 'app:get-snapshot',
  snapshotChanged: 'app:snapshot-changed',
  setConnectionMode: 'connection:set-mode',
  selectDevice: 'device:select',
  listLanNetworks: 'lan:networks',
  searchLan: 'lan:search',
  cancelLanSearch: 'lan:cancel',
  connectTcp: 'connection:connect-tcp',
  repairTcp: 'connection:repair-tcp',
  chooseApk: 'apk:choose',
  parseApk: 'apk:parse',
  loadDeviceApplication: 'application:load-installed',
  loadForegroundApplication: 'application:load-foreground',
  refreshDeviceApplications: 'application:list-installed',
  selectHomeActivity: 'apk:select-home',
  executeCommand: 'command:execute',
  getOperationHistoryDetail: 'operation:get-detail',
  copyOperationSummary: 'operation:copy-summary',
  copyOperationDiagnostics: 'operation:copy-diagnostics'
} as const
