import type { PlatformPermissionApiRange } from '../shared/contracts'

/**
 * 数据来自 Android SDK Platform 36 的 data/api-versions.xml：
 * android/Manifest$permission。这里只保存平台权限常量的 API 生效区间，
 * 运行时仍以目标设备 Package Manager 返回的实际权限定义为最高优先级。
 */
export const ANDROID_PERMISSION_API_METADATA_LEVEL = 36

const API_1_PERMISSIONS = `
  ACCESS_CHECKIN_PROPERTIES ACCESS_COARSE_LOCATION ACCESS_FINE_LOCATION
  ACCESS_LOCATION_EXTRA_COMMANDS ACCESS_MOCK_LOCATION ACCESS_NETWORK_STATE
  ACCESS_SURFACE_FLINGER ACCESS_WIFI_STATE ADD_SYSTEM_SERVICE BATTERY_STATS
  BLUETOOTH BLUETOOTH_ADMIN BRICK BROADCAST_PACKAGE_REMOVED BROADCAST_STICKY
  CALL_PHONE CALL_PRIVILEGED CAMERA CHANGE_COMPONENT_ENABLED_STATE
  CHANGE_CONFIGURATION CHANGE_NETWORK_STATE CHANGE_WIFI_STATE CLEAR_APP_CACHE
  CLEAR_APP_USER_DATA CONTROL_LOCATION_UPDATES DELETE_CACHE_FILES DELETE_PACKAGES
  DEVICE_POWER DIAGNOSTIC DISABLE_KEYGUARD DUMP EXPAND_STATUS_BAR FACTORY_TEST
  FLASHLIGHT FORCE_BACK FOTA_UPDATE GET_ACCOUNTS GET_PACKAGE_SIZE GET_TASKS
  HARDWARE_TEST INJECT_EVENTS INSTALL_PACKAGES INTERNAL_SYSTEM_WINDOW INTERNET
  MANAGE_APP_TOKENS MASTER_CLEAR MODIFY_AUDIO_SETTINGS MODIFY_PHONE_STATE
  MOUNT_UNMOUNT_FILESYSTEMS PERSISTENT_ACTIVITY PROCESS_OUTGOING_CALLS
  READ_CALENDAR READ_CONTACTS READ_FRAME_BUFFER READ_INPUT_STATE READ_LOGS
  READ_OWNER_DATA READ_PHONE_STATE READ_SMS READ_SYNC_SETTINGS READ_SYNC_STATS
  REBOOT RECEIVE_BOOT_COMPLETED RECEIVE_MMS RECEIVE_SMS RECEIVE_WAP_PUSH
  RECORD_AUDIO REORDER_TASKS RESTART_PACKAGES SEND_SMS SET_ACTIVITY_WATCHER
  SET_ALWAYS_FINISH SET_ANIMATION_SCALE SET_DEBUG_APP SET_ORIENTATION
  SET_PREFERRED_APPLICATIONS SET_PROCESS_FOREGROUND SET_PROCESS_LIMIT
  SET_TIME_ZONE SET_WALLPAPER SET_WALLPAPER_HINTS SIGNAL_PERSISTENT_PROCESSES
  STATUS_BAR SUBSCRIBED_FEEDS_READ SUBSCRIBED_FEEDS_WRITE SYSTEM_ALERT_WINDOW
  VIBRATE WAKE_LOCK WRITE_APN_SETTINGS WRITE_CALENDAR WRITE_CONTACTS
  WRITE_GSERVICES WRITE_OWNER_DATA WRITE_SETTINGS WRITE_SMS WRITE_SYNC_SETTINGS
`

const PERMISSIONS_INTRODUCED_AT_API: Readonly<Record<number, string>> = {
  2: 'BROADCAST_SMS BROADCAST_WAP_PUSH',
  3: `
    BIND_APPWIDGET BIND_INPUT_METHOD MOUNT_FORMAT_FILESYSTEMS UPDATE_DEVICE_STATS
    WRITE_SECURE_SETTINGS
  `,
  4: `
    CHANGE_WIFI_MULTICAST_STATE GLOBAL_SEARCH INSTALL_LOCATION_PROVIDER
    READ_HISTORY_BOOKMARKS WRITE_EXTERNAL_STORAGE WRITE_HISTORY_BOOKMARKS
  `,
  5: 'ACCOUNT_MANAGER AUTHENTICATE_ACCOUNTS MANAGE_ACCOUNTS USE_CREDENTIALS',
  8: 'BIND_DEVICE_ADMIN BIND_WALLPAPER KILL_BACKGROUND_PROCESSES SET_TIME',
  9: 'NFC SET_ALARM USE_SIP',
  11: 'BIND_REMOTEVIEWS',
  13: 'SET_POINTER_SPEED',
  14: 'ADD_VOICEMAIL BIND_TEXT_SERVICE BIND_VPN_SERVICE READ_PROFILE WRITE_PROFILE',
  15: 'READ_SOCIAL_STREAM WRITE_SOCIAL_STREAM',
  16: `
    BIND_ACCESSIBILITY_SERVICE READ_CALL_LOG READ_EXTERNAL_STORAGE
    READ_USER_DICTIONARY WRITE_CALL_LOG WRITE_USER_DICTIONARY
  `,
  18: `
    BIND_NOTIFICATION_LISTENER_SERVICE GET_TOP_ACTIVITY_INFO LOCATION_HARDWARE
    SEND_RESPOND_VIA_MESSAGE
  `,
  19: `
    BIND_NFC_SERVICE BIND_PRINT_SERVICE BLUETOOTH_PRIVILEGED CAPTURE_AUDIO_OUTPUT
    CAPTURE_SECURE_VIDEO_OUTPUT CAPTURE_VIDEO_OUTPUT INSTALL_SHORTCUT
    MANAGE_DOCUMENTS MEDIA_CONTENT_CONTROL TRANSMIT_IR UNINSTALL_SHORTCUT
  `,
  20: 'BODY_SENSORS',
  21: `
    BIND_DREAM_SERVICE BIND_TV_INPUT BIND_VOICE_INTERACTION READ_VOICEMAIL
    WRITE_VOICEMAIL
  `,
  22: 'BIND_CARRIER_MESSAGING_SERVICE',
  23: `
    ACCESS_NOTIFICATION_POLICY BIND_CARRIER_SERVICES BIND_CHOOSER_TARGET_SERVICE
    BIND_INCALL_SERVICE BIND_MIDI_DEVICE_SERVICE BIND_TELECOM_CONNECTION_SERVICE
    GET_ACCOUNTS_PRIVILEGED PACKAGE_USAGE_STATS
    REQUEST_IGNORE_BATTERY_OPTIMIZATIONS REQUEST_INSTALL_PACKAGES USE_FINGERPRINT
  `,
  24: `
    BIND_CONDITION_PROVIDER_SERVICE BIND_QUICK_SETTINGS_TILE
    BIND_SCREENING_SERVICE BIND_VR_LISTENER_SERVICE
  `,
  26: `
    ANSWER_PHONE_CALLS BIND_AUTOFILL_SERVICE BIND_VISUAL_VOICEMAIL_SERVICE
    INSTANT_APP_FOREGROUND_SERVICE MANAGE_OWN_CALLS READ_PHONE_NUMBERS
    REQUEST_COMPANION_RUN_IN_BACKGROUND REQUEST_COMPANION_USE_DATA_IN_BACKGROUND
    REQUEST_DELETE_PACKAGES
  `,
  28: 'ACCEPT_HANDOVER FOREGROUND_SERVICE NFC_TRANSACTION_EVENT USE_BIOMETRIC',
  29: `
    ACCESS_BACKGROUND_LOCATION ACCESS_MEDIA_LOCATION ACTIVITY_RECOGNITION
    BIND_CALL_REDIRECTION_SERVICE BIND_CARRIER_MESSAGING_CLIENT_SERVICE
    CALL_COMPANION_APP REQUEST_PASSWORD_COMPLEXITY SMS_FINANCIAL_TRANSACTIONS
    START_VIEW_PERMISSION_USAGE USE_FULL_SCREEN_INTENT
  `,
  30: `
    BIND_CONTROLS BIND_QUICK_ACCESS_WALLET_SERVICE INTERACT_ACROSS_PROFILES
    LOADER_USAGE_STATS MANAGE_EXTERNAL_STORAGE NFC_PREFERRED_PAYMENT_INFO
    QUERY_ALL_PACKAGES READ_PRECISE_PHONE_STATE
  `,
  31: `
    ACCESS_BLOBS_ACROSS_USERS BIND_COMPANION_DEVICE_SERVICE BLUETOOTH_ADVERTISE
    BLUETOOTH_CONNECT BLUETOOTH_SCAN HIDE_OVERLAY_WINDOWS
    HIGH_SAMPLING_RATE_SENSORS MANAGE_MEDIA MANAGE_ONGOING_CALLS
    REQUEST_COMPANION_PROFILE_WATCH
    REQUEST_COMPANION_START_FOREGROUND_SERVICES_FROM_BACKGROUND
    REQUEST_OBSERVE_COMPANION_DEVICE_PRESENCE SCHEDULE_EXACT_ALARM
    START_FOREGROUND_SERVICES_FROM_BACKGROUND UPDATE_PACKAGES_WITHOUT_USER_ACTION
    USE_ICC_AUTH_WITH_DEVICE_IDENTIFIER UWB_RANGING
  `,
  32: 'LAUNCH_MULTI_PANE_SETTINGS_DEEP_LINK',
  33: `
    BIND_TV_INTERACTIVE_APP BODY_SENSORS_BACKGROUND DELIVER_COMPANION_MESSAGES
    MANAGE_WIFI_INTERFACES MANAGE_WIFI_NETWORK_SELECTION NEARBY_WIFI_DEVICES
    OVERRIDE_WIFI_CONFIG POST_NOTIFICATIONS READ_ASSISTANT_APP_SEARCH_DATA
    READ_BASIC_PHONE_STATE READ_HOME_APP_SEARCH_DATA READ_MEDIA_AUDIO
    READ_MEDIA_IMAGES READ_MEDIA_VIDEO READ_NEARBY_STREAMING_POLICY
    REQUEST_COMPANION_PROFILE_APP_STREAMING
    REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION
    REQUEST_COMPANION_PROFILE_COMPUTER REQUEST_COMPANION_SELF_MANAGED
    START_VIEW_APP_FEATURES SUBSCRIBE_TO_KEYGUARD_LOCKED_STATE USE_EXACT_ALARM
  `,
  34: `
    BIND_CREDENTIAL_PROVIDER_SERVICE CONFIGURE_WIFI_DISPLAY
    CREDENTIAL_MANAGER_QUERY_CANDIDATE_CREDENTIALS
    CREDENTIAL_MANAGER_SET_ALLOWED_PROVIDERS CREDENTIAL_MANAGER_SET_ORIGIN
    DETECT_SCREEN_CAPTURE ENFORCE_UPDATE_OWNERSHIP EXECUTE_APP_ACTION
    FOREGROUND_SERVICE_CAMERA FOREGROUND_SERVICE_CONNECTED_DEVICE
    FOREGROUND_SERVICE_DATA_SYNC FOREGROUND_SERVICE_HEALTH
    FOREGROUND_SERVICE_LOCATION FOREGROUND_SERVICE_MEDIA_PLAYBACK
    FOREGROUND_SERVICE_MEDIA_PROJECTION FOREGROUND_SERVICE_MICROPHONE
    FOREGROUND_SERVICE_PHONE_CALL FOREGROUND_SERVICE_REMOTE_MESSAGING
    FOREGROUND_SERVICE_SPECIAL_USE FOREGROUND_SERVICE_SYSTEM_EXEMPTED
    LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE MANAGE_DEVICE_LOCK_STATE
    MANAGE_DEVICE_POLICY_ACCESSIBILITY MANAGE_DEVICE_POLICY_ACCOUNT_MANAGEMENT
    MANAGE_DEVICE_POLICY_ACROSS_USERS MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL
    MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL
    MANAGE_DEVICE_POLICY_AIRPLANE_MODE MANAGE_DEVICE_POLICY_APPS_CONTROL
    MANAGE_DEVICE_POLICY_APP_RESTRICTIONS MANAGE_DEVICE_POLICY_APP_USER_DATA
    MANAGE_DEVICE_POLICY_AUDIO_OUTPUT MANAGE_DEVICE_POLICY_AUTOFILL
    MANAGE_DEVICE_POLICY_BACKUP_SERVICE MANAGE_DEVICE_POLICY_BLUETOOTH
    MANAGE_DEVICE_POLICY_BUGREPORT MANAGE_DEVICE_POLICY_CALLS
    MANAGE_DEVICE_POLICY_CAMERA MANAGE_DEVICE_POLICY_CERTIFICATES
    MANAGE_DEVICE_POLICY_COMMON_CRITERIA_MODE
    MANAGE_DEVICE_POLICY_DEBUGGING_FEATURES MANAGE_DEVICE_POLICY_DEFAULT_SMS
    MANAGE_DEVICE_POLICY_DEVICE_IDENTIFIERS MANAGE_DEVICE_POLICY_DISPLAY
    MANAGE_DEVICE_POLICY_FACTORY_RESET MANAGE_DEVICE_POLICY_FUN
    MANAGE_DEVICE_POLICY_INPUT_METHODS
    MANAGE_DEVICE_POLICY_INSTALL_UNKNOWN_SOURCES
    MANAGE_DEVICE_POLICY_KEEP_UNINSTALLED_PACKAGES
    MANAGE_DEVICE_POLICY_KEYGUARD MANAGE_DEVICE_POLICY_LOCALE
    MANAGE_DEVICE_POLICY_LOCATION MANAGE_DEVICE_POLICY_LOCK
    MANAGE_DEVICE_POLICY_LOCK_CREDENTIALS MANAGE_DEVICE_POLICY_LOCK_TASK
    MANAGE_DEVICE_POLICY_METERED_DATA MANAGE_DEVICE_POLICY_MICROPHONE
    MANAGE_DEVICE_POLICY_MOBILE_NETWORK MANAGE_DEVICE_POLICY_MODIFY_USERS
    MANAGE_DEVICE_POLICY_MTE MANAGE_DEVICE_POLICY_NEARBY_COMMUNICATION
    MANAGE_DEVICE_POLICY_NETWORK_LOGGING
    MANAGE_DEVICE_POLICY_ORGANIZATION_IDENTITY
    MANAGE_DEVICE_POLICY_OVERRIDE_APN MANAGE_DEVICE_POLICY_PACKAGE_STATE
    MANAGE_DEVICE_POLICY_PHYSICAL_MEDIA MANAGE_DEVICE_POLICY_PRINTING
    MANAGE_DEVICE_POLICY_PRIVATE_DNS MANAGE_DEVICE_POLICY_PROFILES
    MANAGE_DEVICE_POLICY_PROFILE_INTERACTION MANAGE_DEVICE_POLICY_PROXY
    MANAGE_DEVICE_POLICY_QUERY_SYSTEM_UPDATES
    MANAGE_DEVICE_POLICY_RESET_PASSWORD
    MANAGE_DEVICE_POLICY_RESTRICT_PRIVATE_DNS
    MANAGE_DEVICE_POLICY_RUNTIME_PERMISSIONS
    MANAGE_DEVICE_POLICY_RUN_IN_BACKGROUND MANAGE_DEVICE_POLICY_SAFE_BOOT
    MANAGE_DEVICE_POLICY_SCREEN_CAPTURE MANAGE_DEVICE_POLICY_SCREEN_CONTENT
    MANAGE_DEVICE_POLICY_SECURITY_LOGGING MANAGE_DEVICE_POLICY_SETTINGS
    MANAGE_DEVICE_POLICY_SMS MANAGE_DEVICE_POLICY_STATUS_BAR
    MANAGE_DEVICE_POLICY_SUPPORT_MESSAGE
    MANAGE_DEVICE_POLICY_SUSPEND_PERSONAL_APPS
    MANAGE_DEVICE_POLICY_SYSTEM_APPS MANAGE_DEVICE_POLICY_SYSTEM_DIALOGS
    MANAGE_DEVICE_POLICY_SYSTEM_UPDATES MANAGE_DEVICE_POLICY_TIME
    MANAGE_DEVICE_POLICY_USB_DATA_SIGNALLING
    MANAGE_DEVICE_POLICY_USB_FILE_TRANSFER MANAGE_DEVICE_POLICY_USERS
    MANAGE_DEVICE_POLICY_VPN MANAGE_DEVICE_POLICY_WALLPAPER
    MANAGE_DEVICE_POLICY_WIFI MANAGE_DEVICE_POLICY_WINDOWS
    MANAGE_DEVICE_POLICY_WIPE_DATA PROVIDE_OWN_AUTOFILL_SUGGESTIONS
    PROVIDE_REMOTE_CREDENTIALS READ_MEDIA_VISUAL_USER_SELECTED
    REQUEST_COMPANION_PROFILE_GLASSES
    REQUEST_COMPANION_PROFILE_NEARBY_DEVICE_STREAMING
    RUN_USER_INITIATED_JOBS TURN_SCREEN_ON
  `,
  35: `
    ACCESS_HIDDEN_PROFILES DETECT_SCREEN_RECORDING
    FOREGROUND_SERVICE_MEDIA_PROCESSING MANAGE_DEVICE_POLICY_ASSIST_CONTENT
    MANAGE_DEVICE_POLICY_BLOCK_UNINSTALL MANAGE_DEVICE_POLICY_CAMERA_TOGGLE
    MANAGE_DEVICE_POLICY_CONTENT_PROTECTION
    MANAGE_DEVICE_POLICY_MANAGED_SUBSCRIPTIONS
    MANAGE_DEVICE_POLICY_MICROPHONE_TOGGLE MEDIA_ROUTING_CONTROL
    READ_DROPBOX_DATA SET_BIOMETRIC_DIALOG_ADVANCED
  `,
  36: `
    APPLY_PICTURE_PROFILE BIND_APP_FUNCTION_SERVICE BIND_TV_AD_SERVICE
    EXECUTE_APP_FUNCTIONS MANAGE_DEVICE_POLICY_APP_FUNCTIONS
    MANAGE_DEVICE_POLICY_THREAD_NETWORK QUERY_ADVANCED_PROTECTION_MODE RANGING
    READ_COLOR_ZONES READ_SYSTEM_PREFERENCES
    REQUEST_OBSERVE_DEVICE_UUID_PRESENCE TV_IMPLICIT_ENTER_PIP
    WRITE_SYSTEM_PREFERENCES
  `
}

const PERMISSIONS_REMOVED_AT_API: Readonly<Record<number, string>> = {
  4: 'ADD_SYSTEM_SERVICE FOTA_UPDATE SET_PROCESS_FOREGROUND',
  9: 'READ_OWNER_DATA WRITE_OWNER_DATA',
  23: `
    ACCESS_MOCK_LOCATION ACCESS_SURFACE_FLINGER AUTHENTICATE_ACCOUNTS BRICK
    CLEAR_APP_USER_DATA DEVICE_POWER FORCE_BACK GET_TOP_ACTIVITY_INFO
    HARDWARE_TEST INJECT_EVENTS INTERNAL_SYSTEM_WINDOW MANAGE_ACCOUNTS
    MANAGE_APP_TOKENS READ_HISTORY_BOOKMARKS READ_PROFILE READ_SOCIAL_STREAM
    READ_USER_DICTIONARY SET_ACTIVITY_WATCHER SET_ORIENTATION SET_POINTER_SPEED
    SUBSCRIBED_FEEDS_READ SUBSCRIBED_FEEDS_WRITE USE_CREDENTIALS
    WRITE_HISTORY_BOOKMARKS WRITE_PROFILE WRITE_SMS WRITE_SOCIAL_STREAM
    WRITE_USER_DICTIONARY
  `,
  24: 'FLASHLIGHT',
  29: 'CAPTURE_SECURE_VIDEO_OUTPUT CAPTURE_VIDEO_OUTPUT READ_FRAME_BUFFER'
}

function names(value: string): string[] {
  return value.trim().split(/\s+/).filter(Boolean)
}

function buildPlatformPermissionApiRanges(): ReadonlyMap<string, PlatformPermissionApiRange> {
  const ranges = new Map<string, PlatformPermissionApiRange>()
  for (const name of names(API_1_PERMISSIONS)) {
    ranges.set(`android.permission.${name}`, {
      introducedApiLevel: 1,
      removedApiLevel: null
    })
  }
  for (const [apiLevel, permissionNames] of Object.entries(
    PERMISSIONS_INTRODUCED_AT_API
  )) {
    for (const name of names(permissionNames)) {
      ranges.set(`android.permission.${name}`, {
        introducedApiLevel: Number(apiLevel),
        removedApiLevel: null
      })
    }
  }
  for (const [apiLevel, permissionNames] of Object.entries(
    PERMISSIONS_REMOVED_AT_API
  )) {
    for (const name of names(permissionNames)) {
      const permissionName = `android.permission.${name}`
      const current = ranges.get(permissionName)
      if (!current) {
        throw new Error(`Android 权限 API 元数据缺少引入版本：${permissionName}`)
      }
      ranges.set(permissionName, {
        ...current,
        removedApiLevel: Number(apiLevel)
      })
    }
  }
  return ranges
}

const PLATFORM_PERMISSION_API_RANGES = buildPlatformPermissionApiRanges()
export const ANDROID_PERMISSION_API_METADATA_COUNT =
  PLATFORM_PERMISSION_API_RANGES.size

export function platformPermissionApiRange(
  permissionName: string
): PlatformPermissionApiRange | null {
  return PLATFORM_PERMISSION_API_RANGES.get(permissionName) ?? null
}
